### ISSUE TITLE
/pages up and download across stores

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#14]
@hughker reported this to me `Page with handle shipping-returns was not found in shop for pages/shipping-returns.html` when trying to d/l pages from one store and upload to another. I know this was also not possible with tmbundle, @internalfx wondering if it could be solved somehow?

**Comment by internalfx** [comment]
Yep, I check to see if a page exists before I push the HTML into it...

Are you wanting me to create the page if it doesn't exist?

Actually, that does make more sense.

**Comment by rickydazla** [comment]
exactly : )

**Comment by hughker** [comment]
@internalfx — :+1: I'd say force create the page if it doesn't exist. Now if only we could get blog posts, link lists, and whatnot via API :smile:

**Comment by internalfx** [comment]
You can get blog posts....

**Comment by rickydazla** [comment]
There is the shop2shop app that does everything but link lists. That would be killer.

**Comment by hughker** [comment]
Hmm… that's kinda tempting to me. Would they just DL to `blogs/blog_name/posts` or something? 

@rickydazla — yeah it does, but i kinda like the idea of being able to create the posts on my local machine and upload too.
