### ISSUE TITLE
Allow explicit call to target

### ISSUE THREAD

**Issue by reggi** [internalfx/quickshot#15]
Currently when you want to run a quickshot command with multiple targets in your quickshot.json file you run `quickshot watch` and have to choose from a dropdown the desired target.

![screen shot 2015-05-07 at 3 39 46 pm](https://cloud.githubusercontent.com/assets/296798/7524337/520ba9d0-f4cf-11e4-9a1e-d7122b7c399f.png)

Ideally you can call the target explicitly from the watch command.

`quickshot watch [target]` / `quickshot watch -t [target]` / `quickshot watch --target [target]`

**Comment by internalfx** [comment]
@reggi you can now do the following...

```
qs download --target=[targetname] [filter]
qs upload --target=[targetname] [filter]
qs watch --target=[targetname]
```
