### ISSUE TITLE
More Ideas!

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#16]
- Products (with metafields... whoah!)
- Collections
- Link lists

Maybe all of the above (and Pages actually) should not be invoked by the regular call to up/download - since they are user-editable (ok, so are the theme files, but they are much more likely to actually be _user-edited_) there is more risk of error / overwrite...

**Comment by rickydazla** [comment]
Also, Blog Articles. There is currently **no** tool that allows bulk editing of these in any way.

**Comment by internalfx** [comment]
- [x] Products
- [ ] Collections
- [ ] ~~Link Lists~~ (No API)
- [x] Blog
- [x] Articles

**Comment by rickydazla** [comment]
@freakdesign how do you interact with link lists within [ShopifyFD](https://github.com/freakdesign/shopifyFD)?

**Comment by freakdesign** [comment]
@rickydazla Since ShopifyFD runs within the admin dashboard I can post data to their internal form endpoints. I also do a bit of html parsing from each linklist page to help gather the any other info I need.

**Comment by rickydazla** [comment]
:balls: you should check this tool out though =>

**Comment by internalfx** [comment]
Most of this is implemented....and wow is this old..
