### ISSUE TITLE
Feature Request » Ignore specific files by default

### ISSUE THREAD

**Issue by hughker** [internalfx/quickshot#18]
- Ignore `quickshot.json` and all `.DS_Store` (recursive)

**Comment by hughker** [comment]
@internalfx — i think all `.DS_Store` and `quickshot.json` files should be ignored by default

**Comment by internalfx** [comment]
Aren't they?

I think I hardcoded the quickshot.json file...

**Comment by internalfx** [comment]
@hughker can this be closed or are you still seeing issues?

**Comment by hughker** [comment]
@internalfx — we can close for now, it might've been a lingering issue with my system. Thanks.

**Comment by internalfx** [comment]
Apparently this is still happening to `.DS_Store` files..

**Comment by internalfx** [comment]
@hughker does this still happen?

Just had a look at the code and I already ignore all hidden files, that _should_ also include `.DS_Store` files.

**Comment by hughker** [comment]
@internalfx it appears that maybe once a `.DS_Store` has been uploaded then it now just thinks it's part of the assets… I'm going to close this for now and if I find the theme I was working on when it happened last I will chat with you about it. But for now, I think we're safe to close.
