### ISSUE TITLE
Best practice workflow

### ISSUE THREAD

**Issue by mcheck** [internalfx/quickshot#20]
Sorry if this seems obvious, but was hoping someone could enlighten me with the best way to work with the tool for local editing since upload and download do not respect deleted pages/products/theme files.

```
mkdir project
cd project
git init .
qs configure
qs theme download
qs products download
qs pages download
git add --all
git commit
git push
```

However, removing pages (for instance) on the shopify site removes the pages, but a `qs pages download` does not remove it from my local. I understand that it is not really a 'sync' per se, but perhaps there is a better way to work and edit with qs that eludes me.

I love the tool by the way, really helps me add more developer speed to editing shopify sites.

Thanks, Mike

**Comment by internalfx** [comment]
The main issue is that if you are just running the commands when you want to update your local or remote copy, I can't (easily) tell if you have deleted any files.

I would say that the `upload` and `download` are mostly for deployment and getting started. Most of the time the intention is that a dev will use `watch`. which _does_ handle all changes, including deletes.

Is there a reason you can't use watch?

I'm wondering if there is a use case I did not consider

**Comment by mcheck** [comment]
No reason at all. Just hadn't tried it, thinking it was simply upload/download depending on where an edit was made. Did not know it handles deletes as well.

How do we manage if changes are made without our knowing, for instance, a client makes a product edit/delete? Essentially changes made without `watch` running? Or maybe this is not an "use while in production" tool?

And sorry for the many Qs, but is there a command to watch all objects at same time? Or start 3 threads...

Thanks!

**Comment by internalfx** [comment]
The tools are separate because of those reasons...

`qs products` doesn't have a `watch` command for example. It's purpose is mostly to move products from one store to another. not for editing.

generally, I imagine most people follow a similar workflow to the below:
1. `qs theme download`
2. `qs theme watch`
3. do work

The other tools `pages`, `products` are _mostly_ for moving stuff between shops. But I think some users use `pages` for editing as well.

**Comment by internalfx** [comment]
You can `watch` pages, and the theme at the same time with 2 terminal windows.

**Comment by mcheck** [comment]
Thanks for the clarification. I appreciate it!

**Comment by internalfx** [comment]
If you have questions in the future. Check out the gitter channel.

https://gitter.im/internalfx/quickshot

You will likely get your questions answered faster there.
