### ISSUE TITLE
Timestamp Terminal Output

### ISSUE THREAD

**Issue by hughker** [internalfx/quickshot#21]
Add a timestamp to the terminal output messages so that you can see exactly when the last action finished. Particularly helpful for users with slower internet now in the boonies who miss their cable/fiber connections. :pensive: 

/cc @rickydazla 

@internalfx I was going to add a "feature-request" tag but I guess I don't have rights to do so, which is why I left it out of the title.

**Comment by rickydazla** [comment]
Actually @internalfx I do see how this could be useful... with my DSL O.o sometimes if I am re-saving same file over and over the upload is instant and sometimes not so much. Tabbing to console obv is not 100% clear unless I know exactly how many times I have hit save. So, yeah :+1:

**Comment by internalfx** [comment]
Added in `v1.2.0`

**Comment by rickydazla** [comment]
:sunglasses:
