### ISSUE TITLE
More detailed error response

### ISSUE THREAD

**Issue by hughker** [internalfx/quickshot#29]
Previously if you were running `qs theme watch` and were trying to upload something with a missing closing tag it would return something like the following: 

```
Error in templates/cart.liquid - Liquid syntax error (line 66): Unknown tag 'endif'
```

However, in v2 it simply responds with: `09:47:08 am - undefined` — it'd be great to have the additional information returned so we can help pinpoint what the error might be.

**Comment by rickydazla** [comment]
`{{ hughkers_comment | plus: 1 }}`

**Comment by rickydazla** [comment]
I am unable to upload any Pages in a particular project but IDK why. Also re: https://github.com/internalfx/quickshot/issues/30

**Comment by internalfx** [comment]
....opening code editor.....

**Comment by rickydazla** [comment]
I just left off an `{% endif %}` on a theme template file and got `undefined`
