### ISSUE TITLE
Pages up/download

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#3]
Would be great if [Pages](https://docs.shopify.com/api/page) could also be down/uploaded.

**Comment by internalfx** [comment]
I'll look into this...

**Comment by internalfx** [comment]
Working on this now

**Comment by hughker** [comment]
@internalfx — leaving open or does 774a8acdd3c153f4be02db9cb84b10607af5b6fa close this?

**Comment by internalfx** [comment]
yeah...it does
