### ISSUE TITLE
[Pages] Cannot overwrite?

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#37]
If I download a page and modify I cannot re-upload. I get error `{"handle":["has already been taken"]}`. This is a significant degradation in functionality since 1.x where we could also watch pages: https://github.com/internalfx/quickshot/issues/28 — the major advantage of quickshot previously was that I never had to use the Shopify admin panel, now I do again..

**Comment by internalfx** [comment]
I'm closing this as quickshot has changed considerably.
