### ISSUE TITLE
theme upload error

### ISSUE THREAD

**Issue by trajce** [internalfx/quickshot#39]
when i go `qs theme upload` i get response like this

```
07:25:28 pm - Request Failed!: [404] Not Found
{"key":"theme/assets/android-chrome-36x36.png"}
```

on multiple stores. Nothing happens after that, no message whether the upload was successful or aborted. Btw, the asset that are "not found" actually exist. 
im on windows 8.1, using quickshot v2.1.3

**Comment by thsbrown** [comment]
I'm getting the exact same error :(

**Comment by romulobordezani** [comment]
Same for me on Windows 8.1 - qs 2.1.3

**Comment by internalfx** [comment]
I'm closing this as quickshot has changed considerably.
