### ISSUE TITLE
Ignore files in .gitignore

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#4]
Might be useful...

**Comment by internalfx** [comment]
Ah..I like that.

Very logical to use the .gitignore file to exclude files for upload/download

**Comment by rickydazla** [comment]
Yeah, I usually ignore `settings_data.json` and related file uploads.

**Comment by hughker** [comment]
@internalfx agree with this as well — was just about to open an issue but knew my buddy @rickydazla was already ahead of me. Maybe even a global ignore for `.DS_Store` files would be nice too. 

Although one potential issue I see with using `.gitignore` would be that we'd have to include something like the `README.md` and we use it for our devs for specific information for each repo. 

What're the thoughts on a `.ignore` file, that way it would still be separate from the `.gitignore` but you could make it unique enough for your specific needs.

**Comment by internalfx** [comment]
thanks @hughker.

Makes sense that what you want in git might not always parallel what you want uploaded. I agree we will need more than just a `.gitignore`

**Comment by internalfx** [comment]
I think this is the next feature to get implemented...

If anyone has any input on what they would like to see, now is the time to speak up.

**Comment by internalfx** [comment]
Fixed in `0.6.0`

Quickshot now supports ignore files.

You can use your projects `.gitignore` file, or you can use a custom `.quickshotignore` file. Your choice.

Both files use the same syntax.
