### ISSUE TITLE
Will you provide an example on how to use options and filters?

### ISSUE THREAD

**Issue by t-fulton** [internalfx/quickshot#42]
Specifically, I'm trying to download a specific file from a specific target.

**docs provide this:**
`qs theme download [options] [filter]`

**I'd think that this would work, but it doesn't**
`qs theme download --target dev --filter page.dealer-intl.liquid`

Thanks!

**Comment by hughker** [comment]
@t-fulton you would do something like the following:

` quickshot theme download --target=Live theme/assets/your_file`

Lemme know if you need anything else!

**Comment by t-fulton** [comment]
@hughker Thanks!

**Comment by hughker** [comment]
@t-fulton actually I might've given you incorrect information, it should be:

`quickshot theme download --target=your_target assets/your_file`

You don't need the `theme/` in the last part
