### ISSUE TITLE
Unable to update pages in target if pages already exist

### ISSUE THREAD

**Issue by t-fulton** [internalfx/quickshot#43]
I have two shopify environments, I'll call them A and B. I've transferred pages from A to B in the past. I've since added some pages to A and would like transfer all the pages to B (to get the new pages I added in A into B). However, I get the following error when I try the upload:
`{"handle":["has already been taken"]}`

Am I doing something wrong or is it not possible to do this? Do I have to delete all the pages from B first (that would be a bummer).

Thanks.

**Comment by MarioRicalde** [comment]
As of right now - the current solution is to delete the pages from the target environment to ensure that the sync is good.

Also, from what I can tell collections are not kept.

**Comment by t-fulton** [comment]
Unfortunately that also nukes the associated menus forcing you to recreate them. This fork addresses this issue nicely though https://github.com/kevinhaugen/quickshot-redux

**Comment by rickydazla** [comment]
@t-fulton why don't you create a PR against this repo?

**Comment by rickydazla** [comment]
Also FWIW this is a duplicate of #37

**Comment by internalfx** [comment]
I'm closing this as quickshot has changed considerably.
