### ISSUE TITLE
"Undefined" doesn't give enough information when using theme watch

### ISSUE THREAD

**Issue by ironic-name** [internalfx/quickshot#44]
While using `theme watch` saving an invalid file shows "{timestamp} - undefined".

This in itself is perfectly fine, and expected. Is it possible to have a description of the offending issue that prevents the theme upload? 

When I copy the contents of the file into the Shopify editor and attempt to save the file I get an error block above the editor of where the problem is, which makes it quick to find and update the issue. It would be amazing if Quickshot could have this kind of feature too.

**Comment by internalfx** [comment]
It's certainly possible.

And also a good idea.

I should probably add that this repo is basically abandoned at this point as I no longer work on Shopify sites.

If you want to send me a PR, I'll take a look.
