### ISSUE TITLE
Node-Sass binding error

### ISSUE THREAD

**Issue by celsowhite** [internalfx/quickshot#45]
I recently updated my node environment to v8.9.1 and encountered an error when running qs theme watch. The node-sass binding was incorrect for my runtime environment.

Quickshot uses node-sass 3.13.1. That version is only supported within node environments up to version 7 https://github.com/sass/node-sass/releases/tag/v3.13.0.

To fix this I navigated to quickshots global npm module - /usr/local/lib/node_modules/quickshot and ran:

`npm rebuild node-sass`

That seems to have worked for me and I'm now able to run qs theme watch command.

Is that the correct method to fix the issue?

**Comment by heyivanvilla** [comment]
@celsowhite you saved me much much headache. I was also facing this issue.

**Comment by rickydazla** [comment]
... or `nvm use 7`
