### ISSUE TITLE
Theme Upload Clears Customizer Settings

### ISSUE THREAD

**Issue by celsowhite** [internalfx/quickshot#47]
Heads up to anyone heavily using the Shopify customizer. I've found that a full 'qs theme upload' will clear your customizer settings.

A solution is to make sure your settings_data.json is downloaded from your live site so it is up to date. Also don't include theme/config/settings_data.json in your .quickshotignore.

**Comment by hughker** [comment]
@celsowhite right, yes, it's always best practice to do a `quickshot theme download` before working on the site for that exact reason — I've ran into that issue several times before as well. 👍
