### ISSUE TITLE
Sass interpolation with variables and liquid

### ISSUE THREAD

**Issue by joshuaiz** [internalfx/quickshot#48]
Hello, 
Just getting into quickshot and liquid. I've taken over development of a retail e-commerce site that already has a pre-made theme. In trying to set up my local development environment, I've gone through and split out the main styles.scss.liquid file into modular stylesheets, interpolated all of the liquid calls and importing all of the modules into main stylesheet to be precompiled and output before pushing.

Nevertheless, I'm getting some errors with some more complex liquid calls in the pre-made theme, especially when variables are referenced elsewhere in the stylesheets.

Here's an example of the original code in styles.scss.liquid:
     
     {% if settings.body_font contains 'GWF' %}
     {% capture gfont %}{{ settings.body_font | split: '|' | last }}{% endcapture %} 
     {% else %}{% assign gfont = settings.body_font %}
     {% endif %}
     $body-font-family: {{ gfont | replace: '+', ' ' | replace: "'", '' | split: ':' | first | default: 'sans-serif' }}, sans-serif;

Which I've interpolated to:

     /* {% if settings.body_font contains 'GWF' %} */
     /* {% capture gfont %} */
     /* {{ settings.body_font | split: '|' | last | prepend: '*\/' | append: '\/*' | remove: '\' }} */
     /* {% endcapture %} */
     /* {% else %} */
     /* {% assign gfont = settings.body_font %} */
     /* {% endif %} */
     $body-font-family: #{' {{ gfont | replace: "+", " " | replace: "\'", "" | split: ":" | first | default: "sans-serif" }} '}, sans-serif;

When I use that, I get this error in the compiler:

     Error: Invalid CSS after "...| remove: '\\' }": expected selector or at-rule, was "} */" on line 13 of /theme/styles/_typography.scss
     >> :\" | first | default: \"sans-serif\" }} "}, sans-serif;

I've looked over everything I can find on liquid/sass interpolation and not having any luck. As variables like `$body-font-family` are called elsewhere in the stylesheets, if I can't get this to compile, I get errors elsewhere.

Thanks!

**Comment by hughker** [comment]
@joshuaiz perhaps I'm missing something, but this doesn't seem like an issue with Quickshot rather a limitation of Shopify's SASS Compiler?

**Comment by joshuaiz** [comment]
Hi @hughker, 

I'm getting this error in the qs compiler locally.

Previously I tried using CodeKit to compile my scss files and was getting the error above with the CodeKit libsass compiler but bypassing CodeKit completely and using the built-in qs compiler I am getting basically the same error:

     Error: Invalid CSS after '... "sans-serif" }': expected selector or at-rule, was "} '};"
    at Object.module.exports.renderSync (/usr/local/lib/node_modules/quickshot/node_modules/node-sass/lib/index.js:434:16)
    at /usr/local/lib/node_modules/quickshot/lib/theme/watch.js:61:29
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/quickshot/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/quickshot/node_modules/co/index.js:54:5
    at Promise._execute (/usr/local/lib/node_modules/quickshot/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/quickshot/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/local/lib/node_modules/quickshot/node_modules/bluebird/js/release/promise.js:79:10)
    at co (/usr/local/lib/node_modules/quickshot/node_modules/co/index.js:50:10)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/quickshot/lib/theme/watch.js:40:12)
    at FSWatcher.emit (events.js:160:13)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/quickshot/node_modules/chokidar/index.js:197:38)
    at FSWatcher._emit (/usr/local/lib/node_modules/quickshot/node_modules/chokidar/index.js:238:5)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/quickshot/node_modules/chokidar/lib/nodefs-handler.js:268:12)
    at /usr/local/lib/node_modules/quickshot/node_modules/chokidar/lib/nodefs-handler.js:176:13
    at Array.forEach (<anonymous>)

I'm still at a loss on how to interpolate that. Or maybe I should just leave it alone as it will just pass through to the compiled css.liquid file?

On another note but related: if I want to put my styles in a /styles sub-folder in my theme (which I know will be ignored by Shopify) and set my main application.scss file there, will qs compile that into the assets folder as application.css.liquid or in the same folder? Also, does the qs compiler work with standard modular scss files with an underscore like _base.scss, _typography.scss, etc.? Or do we need to remove the underscores?

Sorry for the noob questions, I'm coming from the WordPress universe and just trying to get our local development environment set up.

**Comment by hughker** [comment]
@joshuaiz oh gotcha, sorry, I've never used that feature of it. I compile my SCSS outside of Quickshot and then in my `site-styles.scss.liquid` I do any liquid checks in there as I've never been able to get it to successfully parse a SCSS file with Liquid in it. 

Perhaps @internalfx might be able to provide better insight into this; however, working with Shopify will require you to change your typical workflow anyways due to some of their limitations: so perhaps this might just be one of them…

**Comment by joshuaiz** [comment]
@hughker cool. I'd like to keep using CodeKit but it looks like instead of getting into interpolation hell, I might have to maintain clean scss files with our changes and leave the xxx.scss.liquid files as-is unless @internalfx can shed some light on this.

**Comment by internalfx** [comment]
@joshuaiz 

look here
https://www.shopify.com/partners/blog/a-beginners-guide-to-sass-with-shopify-part-3

Look specifically at the section titled "Using Liquid in Sass files"

**Comment by joshuaiz** [comment]
Hi @internalfx, thanks but I've looked through that as well as everything else I can find on sass interpolation + liquid and using that method as shown here:

     $body-font-family: #{' {{ gfont | replace: "+", " " | replace: "\'", "" | split: ":" | first | default: "sans-serif" }} '}, sans-serif;

I think the issue lies in the single and double quotes used in the liquid call in the example I provided but even escaping those quotes as I've done above within the call still gives me an error.

What am I missing here?

**Comment by internalfx** [comment]
just to be sure, have you removed every other line from the file except that one?

In this case I would not just comment it out.

**Comment by joshuaiz** [comment]
@internalfx That particular line is not commented out but rather interpolated. The only things "commented" are the liquid if/else statements which is done as per various guides on sass interpolation and liquid e.g.:

     {% if settings.body_font contains 'GWF' %}

is interpolated to:

     /* {% if settings.body_font contains 'GWF' %} */

(along with the rest of the if/else statement)

The actual scss variable call with liquid is *not* commented out:

    $body-font-family: #{' {{ gfont | replace: "+", " " | replace: "\'", "" | split: ":" | first | default: "sans-serif" }} '}, sans-serif;

I realize this is somewhat outside the scope of Quickshot itself.

I had already posted in the comments on the sass interpolation page you linked above as well as on the Shopify forums and no one seems to know how to interpolate this. 

What I might have to do is just hard code the font choices in the theme so at least I can get the scss to compile. This is coming from a theme setting where the client can choose the Google font but if we *know* what the font will be we don't need to grab this programmatically.

All that said, it would be good to know how to interpolate something like this in case I come across it in the future.

Thanks!

**Comment by internalfx** [comment]
I was suggesting to try the problematic line of code in a sass file by itself.

**Comment by joshuaiz** [comment]
@internalfx gotcha. Tried that and get the same error when trying just to compile that single line.

**Comment by internalfx** [comment]
just wanted to eliminate all possible side effects.

what happens if you remove `\'` from the file?

I know it won't be the correct output, just looking for the smoking gun.

**Comment by joshuaiz** [comment]
Same error. And same error even if I remove this bit comepletely: `replace: "'", ""`

Here is the error:

     Libsass: Error: Invalid CSS after "$body-font-family:": expected expression (e.g. 1px, bold), was "#{' {{ gfont | repl"
        on line 1 of _dev/theme/styles/_test.scss
       >> $body-font-family: #{' {{ gfont | replace: "+", " " | split: ":"" | first | de

**Comment by internalfx** [comment]
We need to find the lowest common denominator.

What does the below do?

```
$body-font-family: #{' {{ test }} '}, sans-serif;
```

**Comment by joshuaiz** [comment]
That compiles. If I take out anything with quotes in the original variable, it compiles as well.

**Comment by internalfx** [comment]
Does it work better with `"`?


perhaps the below?
```
$body-font-family: #{" {{ gfont | replace: \"+\", \" \"}} "}, sans-serif;
```

**Comment by joshuaiz** [comment]
Now this is interesting...

These compile:

     $body-font-family: #{" {{ gfont | replace: \"+\", \" \"}} "}, sans-serif;

     $body-font-family: #{" {{ gfont | replace: \"+\", \" \" | split: \":\" | first | default: \"sans-serif\" }} "}, sans-serif;

But this does not:

     $body-font-family: #{" {{ gfont | replace: \"+\", \" \" | replace: \"'\", \"\" | split: \":\" | first | default: \"sans-serif\" }} "}, sans-serif;

It doesn't like that extra single quote at all.

The other thing to note also is that after compiling this, no css is output so I would have to output to a xxxx.scss.liquid file so that Shopify could compile that at runtime.

**Comment by internalfx** [comment]
The main purpose of quickshot local scss compilation, is that you could use the @import feature.

So that you can bundle all your scss together, which helps loading time.

So it actually doesn't output `.scss.liquid` by design.

it outputs `.css.liquid` which is all you need.

**Comment by joshuaiz** [comment]
Got it. I have it set up now as per the qs instructions to output xxxx.css.liquid.

Now having this error with calls like this:

Original:

     $background-col: {{ settings.site_bg_col }};

Interpolated:

     $background-col: #{' {{ settings.site_bg_col }} '};

Called later in scss file (causing compile error):

    $input-border-col: mix($input-text-col, $background-col, 30%);

Error: 

     Error: argument `$color-2` of `mix($color-1, $color-2, $weight: 50%)` must be a color

There of lots of cases like this where it is grabbing a value from the settings which is then used in a mixin/sass function later and they are all causing errors. How can I get around this?

Thanks a lot for the help.

**Comment by internalfx** [comment]
Short answer....you can't

Long Answer:

What you are trying to do there doesn't work because scss compiling happens before the liquid compiling.

So you are trying to set an scss variable to a color that won't be known until the liquid is processed, which happens after all the scss is long gone.

**Comment by joshuaiz** [comment]
Got it. So I think my options at this point are to 1) hard code the values in; or 2) fill the variables from the settings_data.json file using something like this:

https://github.com/vigetlabs/sass-json-vars (using Ruby)
https://github.com/Updater/node-sass-json-importer (using Node)

Option #1 is easiest but option #2 will allow for the client to update the theme settings in the Shopify admin and as long as I keep the settings_data.json file current locally, that should work.

Thanks again for the help and the tangent...I'll mark this as closed. Maybe I can even start editing some theme code one of these days!

**Comment by internalfx** [comment]
best of luck
