### ISSUE TITLE
Theme Management (Primary / unspecified)

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#5]
Two points here within quickshot config:
- it would be useful (for me, at least) to know which is the primary/live theme within the A-Z list for easy ID purposes. Otherwise I may have to login to store admin panel to check which is live when they are not named sensibly.
- having option to leave the underlying theme.id blank and set up a particular target for "whichever theme is live" would also be cool.

**Comment by internalfx** [comment]
To the first: done!

To the second, IMHO I think its best to have the user be explicit, especially because we would by default overwrite the _live_ theme.

**Comment by rickydazla** [comment]
@internalfx re: second option I agree it should be an explicit choice, but having that choice would be super-helpful. You could have an additional warning dialog...

**Comment by internalfx** [comment]
Does having the theme selector display which theme is 'main' not fix the problem?

I guess what I'm not getting is the only benefit I could see is the following scenario would be possible...
- User creates new config and chooses no theme (defaulting to live one)
- User makes changes, whatever
- User switches which theme is live on Shopify
- quickshot now uploads/downloads to a different theme than before

Do I understand correctly? Is this a desired outcome :confused:

**Comment by rickydazla** [comment]
I focus my workflow on just the live theme in any / every store... I would prefer to set two/three targets for dev, staging, live, with each using "whatever theme is live". I very rarely use the API to up- or download files to/from a theme that is not the primary and if I did I would know to specify.

**Comment by rickydazla** [comment]
(of 30+ clients I only have one config file set with a theme ID and that is where they are using an old school mobile theme so actually have two that are live)

**Comment by rickydazla** [comment]
Other devs I know use multiple themes in the same store and use the "Preview" function, rather than having distinct staging/dev stores set up. They would obviously need to use the theme id..

**Comment by internalfx** [comment]
ok, I'll think about this some more...

In the mean time you can now see which theme is live, so you can select it explicitly for now.

I'll leave this open for more comments from other users (assuming we have any :laughing:)

**Comment by rickydazla** [comment]
I'm sure @hughker might have something to say once he figures out how to install the thing.

cc: @trajceoh @jayvin @feddyups @gavinballard @reggi @freakdesign

**Comment by reggi** [comment]
@rickydazla  thanks for sharing! 

I have a much different stack with much different needs. For starters I only work on one theme. I'm primary using a series of bash commands for uploading the theme

This uses:
- https://github.com/alloy/terminal-notifier
- https://github.com/Shopify/shopify_theme

> ./build_scripts/shopify.sh

``` bash
terminal-notifier -title Shopify -sound Tink -message "Shopify theme being watch" -group shopify
cd ./theme &&
theme watch |
sed -E -l -e 's/.+ Uploaded: (.+)/\1/' |
xargs -I output terminal-notifier -title Shopify -sound Tink -message output -group shopify
```

and I have this in my `package.json` for the theme:

``` json
"scripts": {
  "shopify": "sh ./build_scripts/shopify.sh",
}
```

So I get theme watching with `npm run shopify`. I'm also using `less` for css (via grunt which I need to get off) and `webpack` for js, with their own commands in `scripts`.

I'm still on the old `theme` bash command (https://github.com/Shopify/shopify_theme) but they shopify people are working on a better one https://github.com/csaunders/phoenix which I will move to [they've done a great job of fixing it up lately](https://github.com/csaunders/phoenix/issues?q=is%3Aissue+author%3Areggi+is%3Aclosed).

@rickydazla With all that said I really don't know the purpose of this project. I don't wanna bash it, and I'm glad that it's out there and being shared. But I don't get why it's an uploader, config wizard, and scss generator all in one, seems like it's doing way too much. Plus you guys are doing the only thing I criticized phoenix for [Package management](https://github.com/csaunders/phoenix/issues/15), you're using NPM (:clap:), all of those things can be split up into smaller things and you can add what you need. Just some thoughts :)

**Comment by internalfx** [comment]
@reggi so it has too many features?

You can use as much or as little of the features as you want...nothing is forced.

Some points:
- The configuration wizard is purely to setup quickshot properly, so that files are sent to the correct place. And so options can be enabled/disabled.
- Scss compiling is just an option, also enabled or disabled in the configuration.

I get the impression you didn't actually try it out. Just read the docs? Maybe I need to do a better job of writing those....

If you only wanted something to upload your files, you could get just that.

**Comment by reggi** [comment]
@internalfx Hey! Your totally right! I should have tried it before bashing :smile_cat: 

How do you run it? You documentation mentions `quickshot configure` but you don't say what actually runs quickshot? Does it watch automatically? Does it push on command?

**Comment by internalfx** [comment]
quickshot runs on node. So it has to be installed with `npm install -g quickshot`.

the `-g` installs quickshot globally and makes the `quickshot` command available at the systems terminal.

Installed correctly, you can run it from anywhere. :smile:

Also if you run `quickshot` with no arguments it will list all the available commands.

**Comment by internalfx** [comment]
I can probably be of more help on the gitter channel

https://gitter.im/internalfx/quickshot

**Comment by reggi** [comment]
After using it, I moved off of it from https://github.com/Shopify/shopify_theme

Works really nice with terminal notifier `quickshot watch | xargs -I output terminal-notifier -title Shopify -sound Tink -message output -group shopify`.

Plus it has a delete function :)

Only problem is I cant set theme directory when I configure. and I have to run something like `cd ./theme && quickshot watch`, not a big deal though.

**Comment by internalfx** [comment]
@rickydazla Is this still an issue?

**Comment by rickydazla** [comment]
@internalfx what you have right now has been working really well for me this week (back from vacation and catching up with several theme-related projects), although I still think that having the option to leave the underlying theme.id blank and set up a particular target for "whichever theme is live" would be useful.. It's not a biggie though and happy to close if you think it could come back to bite.

**Comment by internalfx** [comment]
@rickydazla My thoughts on this are that it doesn't appear to be too inconvenient for the user. (your last comment seems to echo that) But my fears on the feature are as follows:
- If another user (or the client) sets another theme live, you are now editing a different theme. Maybe without your knowledge!
- Our docs are pretty sparse right now, and this would need to be clearly documented (with warnings!).

For now, I have decided to close.
