### ISSUE TITLE
Specificity / selection of resources

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#59]
I wasn't really sure how to title this issue correctly, although it's easy to explain...

If I run e.g. `qs theme download config --target=live` in version 2.x I would have got only the contents of the config folder, whereas now the `config` argument in the command is ignored.

**Comment by internalfx** [comment]
I scrutinized every feature.

I wasn't sure how much this was used, also the way I implemented it was confusing I think.

If it's useful I can certainly bring it back.

**Comment by rickydazla** [comment]
I use it quite a bit for download and upload, a syntax change certainly wouldn’t bother me!

**Comment by internalfx** [comment]
Version `3.1.0` Released
