### ISSUE TITLE
Concurrency / API limit handling

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#60]
I believe in v2.x when the API limit was exceeded there was a log message to the effect "API limit exceeded, will retry." which was amazing, instead I just ran into this, and the process aborted:

```
09:40:50 pm - 429 - {"errors":"Exceeded 4 calls per second for api client. Reduce request rates to resume uninterrupted service."}
=== START OF OUTPUT ===
{ errors: 'Exceeded 4 calls per second for api client. Reduce request rates to resume uninterrupted service.' }
==== END OF OUTPUT ====
```

**Comment by internalfx** [comment]
hmmm....the retry code is still in-place so this should have worked as before.

I'll take a look

**Comment by internalfx** [comment]
`3.0.9` published
