### ISSUE TITLE
Pages & Blog Articles

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#61]
I miss `qs pages download` && `qs blogs download` 😭

**Comment by internalfx** [comment]
Good to know, I wasn't sure if it was useful.

**Comment by rickydazla** [comment]
@internalfx people be 4kin up the internal rich text editor content added via admin... I used to pull down Pages and Blog Articles so that I had a "back up" but now if someone edits something and messes with the HTML then 💥 .. gone. Halp!

**Comment by internalfx** [comment]
Gotcha....maybe a content backup capability would be useful

**Comment by rickydazla** [comment]
🙏

**Comment by joshuaiz** [comment]
Another vote for this feature - for me it is super useful.

**Comment by internalfx** [comment]
@joshuaiz @rickydazla

Experimental pages support has landed in quickshot 3.3

A lot of thought went into a new file format.

One of the things I very much disliked about pages support in V1 was the fact that it wasn't very useful for editing the file in an editor.

This new version allows you to edit it as HTML as long as you don't disturb the top section (It should make sense once you see it).

Please test and provide feedback.

**Comment by hughker** [comment]
I personally miss the "Rocket Code Clone" App. :] — where it basically literally cloned the store from live » dev for me. Can't wait to check out this feature! Thank you @internalfx!!

**Comment by internalfx** [comment]
@hughker @rickydazla @joshuaiz Any feedback on the new pages file format?

My hope is that the format is useful when you actually need to edit the files.

**Comment by internalfx** [comment]
If there are no problems, I intend to use the same format for blogs.

**Comment by rickydazla** [comment]
@internalfx apologies for delayed response, i think the new format is great. Having the meta included as comment in content file is great. Using same format for Blog Articles would be 👌 ... Any chance of getting `qs pages watch` / `qs articles watch`?

**Comment by rickydazla** [comment]
So I have to edit a whole bunch of blog articles because we are getting sued under the ADA for not having alt text and non-semantic HTML... This functionality would be _awesome_ right now! In lieu of that, can someone remind me how to run the older version of quickshot?

**Comment by internalfx** [comment]
@rickydazla experimental blog support has landed in the latest version.

Please try it out and let me know how it goes.

Also pinging @hughker @joshuaiz

**Comment by internalfx** [comment]
@rickydazla @hughker @joshuaiz Product support has landed in `3.5.0`

And yes, metafields are included, so your copycat stuff moves too.

enjoy!

**Comment by rickydazla** [comment]
@internalfx I haven't tried products yet but blogs/articles is exactly it. 🙏

**Comment by joshuaiz** [comment]
Had to use the blogs feature and it worked perfectly — thanks for adding this back in!

Only minor issue is it doesn't keep the blog post date(s). Not a huge deal in my case as we were moving from a production site to a staging site but if you were going from staging to production, you might want to keep the post dates especially if you use those for sorting. 

Just thought I'd mention this in case date persistence could be added in a future update.
