### ISSUE TITLE
404 undefined on theme upload

### ISSUE THREAD

**Issue by valespring** [internalfx/quickshot#62]
Hi there, I currently manage two stores and utilize QS on both, which has been working great. I updated to the latest version and config, and one of them works when invoking 'qs theme upload', while one simply does not. 'qs theme watch' works as normal.

It produces the following error:

<img width="519" alt="Screen Shot 2019-05-01 at 1 18 14 PM" src="https://user-images.githubusercontent.com/6156288/57033927-d548b080-6c13-11e9-96ae-0fb4c9b53e67.png">

Any ideas on how to troubleshoot or what this pertains to? I've reconfigured twice, and details are similar if not the same between both projects.

Thanks!

**Comment by internalfx** [comment]
Interesting...Do you have any folders in your theme folder that Shopify doesn't have/allow?

**Comment by valespring** [comment]
Yes, that did the trick! I had an apps folder I used for storing templates for a third-party app, so I just added it to the quickshot-ignore file and tested it again.

**Comment by internalfx** [comment]
Cool, thanks for letting me know how I can reproduce this.
