### ISSUE TITLE
CSS file not posting during 'qs theme watch'

### ISSUE THREAD

**Issue by valespring** [internalfx/quickshot#65]
Hey there, I'm experiencing a somewhat odd error on a new customer store. I set up my workflow with Gulp like pretty much every other project. There are three main tasks included in the default task:

- Scripts
- CSS
- Icons

On task compilation, I literally see the output CSS file change in theme/assets, but it does not trigger an upload with the main css file. It only uploads the changed icons. I've verified that it does output to the theme/assets folder, as I've deleted and re-tested this theory a few times. JS also uploads fine, strangely.

<img width="437" alt="Screen Shot 2019-07-21 at 11 19 10 PM" src="https://user-images.githubusercontent.com/6156288/61606124-67a69200-ac0e-11e9-891e-0bda2c94f9fc.png">

 

Any ideas? This is my current qs-ignore:

```# This your '.quickshotignore' file. Anything you put in here will be ignored by quickshot.
# This file uses the same format as a '.gitignore' file.

# Base
.gitignore
.DS_Store
theme/assets/.DS_Store
theme/apps/

# Configs
theme/config/settings_data.json
#theme/config/settings_schema.json

# Languages
theme/locales

README.md```

**Comment by valespring** [comment]
I created a gulp clean task just as a workaround for now since it works if I delete and reupload, but hoping it's a simple fix ~

**Comment by internalfx** [comment]
are you running version 3?

also what operating system are you on?

**Comment by valespring** [comment]
Quickshot 3.1.0

OSX - 10.12.6 (16G2016)

**Comment by internalfx** [comment]
@valespring I wanted to follow up on this, did you ever learn anything else about this issue?

**Comment by internalfx** [comment]
@valespring Assuming this is fixed now...please re-open if the problem persists
