### ISSUE TITLE
Option to name theme folder.

### ISSUE THREAD

**Issue by joshuaiz** [internalfx/quickshot#67]
Hello,
I have multiple stores I'm using Quickshot with and when downloading the default theme name is "theme". Yet when I have multiple "theme" folders in my editor it is hard to keep track of which theme is which.

When creating a target, it would be great to be able to choose a custom theme name.

I know I can change it after however if I've created the target, then run `qs theme download` and *then* change the theme folder name, QS downloads all of the files again. 

It would be great to name the folder upon target creation to avoid this issue.

**Comment by internalfx** [comment]
Interesting idea...

@rickydazla @hughker Can you chime in?

Would this negatively impact anyone's workflow?

**Comment by hughker** [comment]
@internalfx so long as the default is to just keep it `theme` it doesn't matter to me. However, every single store I work on has its own unique repo so I have no need to rename it whatsoever. Pretty sure @rickydazla will say something similar.

**Comment by joshuaiz** [comment]
What I've done instead is keep each store in their own directory and then add that top level directory to my editor (each with its own `theme` sub-folder) to keep things organized locally.

All that said, I could see a situation where you'd have multiple themes per store (e.g. Preview themes and live themes) so it would be good to be able to keep all of these in a single directory. I'm not sure how QS would handle this however.

**Comment by internalfx** [comment]
I can see a possibility of letting users configure the name of the folder per target.

The default would of course be `theme` but if changed then basically all actions would operate with the assumption that all files exist in the targets configured folder name.

**Comment by hughker** [comment]
I mean I guess do whatever works for you! Typically for my clients and workflow, `master` is always the current liveTheme as we have setup auto-deploy workflows once a PR is Merged. 

Then of course whatever you’re working on would’ve been branched off `master` and then. PR submitted. 

At the end of the day, if you feel like doing this feature request @internalfx I guess it doesn’t matter to me so long as the default behavior remains the same. But seems to me like an edge case to me. 💁‍♀️

**Comment by joshuaiz** [comment]
Yes I agree it is an edge case and I don't really need it anymore.

All that said, @hughker can you elaborate on how you have deployment set up to Shopify based on a PR. One of my clients is expanding the team and I think we could adopt this workflow.

**Comment by internalfx** [comment]
thanks for the discussion guys, closing.
