### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#68]
I've started getting more and more of these, which quits the process (e.g. qs theme up-/download):

```
12:46:24 pm - Error: connect ETIMEDOUT 23.227.38.64:443
=== START OF OUTPUT ===
Error: connect ETIMEDOUT 23.227.38.64:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '23.227.38.64',
  port: 443
}
==== END OF OUTPUT ====
```

A whois lookup confirms the IP address is one of Shopify's. I tried dialing the concurrency back to 1, but still get the above after ~20 requests.

Is there any way to get the process to queue / re-try and not quit?

**Comment by internalfx** [comment]
probably, I'm surprised it's not already written that way.

I'll need to do some testing....

**Comment by rickydazla** [comment]
I think this is a connection issue. I usually access via either my mobile hotspot or more recently a captive portal at my office building. I think the latter is a little... shaky. However, it does seem that there is still _some_ connectivity when the above errors occur. A timeout on one connection seems to quit all of the processes

**Comment by internalfx** [comment]
I've reworked the module that talks to Shopify to make it more resiliently use (abuse? :smirk: ) your internet connection. Version 3.2 published.

This version will repeatedly try to transmit files, I tested it by constantly enabling/disabling my network adapter while doing a `qs theme download`

**Comment by rickydazla** [comment]
Yesss! Confirmed awesome: `02:59:28 pm - Downloaded 840 files.` (Custom themes gettin bigger and bigger!) I did see a couple of "Timeout, will retry..." too, which previously would have aborted. This is great 🙏
