### ISSUE TITLE
403 Error during configuration

### ISSUE THREAD

**Issue by emiremiroglu** [internalfx/quickshot#69]
Today, I had a go with this CLI but getting 403 error during setup. (Just after entering shop URL)

NPM 6.13.0
NODE v10.11.0

Any ideas what it would be. I'm new to this tool please let me know if I'm doing something wrong.

Merry Christmas!

<img width="678" alt="Screen Shot 2019-12-25 at 15 13 34" src="https://user-images.githubusercontent.com/8298129/71445222-06d53580-2729-11ea-93c8-6a865656d15b.png">

**Comment by internalfx** [comment]
The URL you pasted does not have the api keys so Shopify is rejecting your request.

**Comment by internalfx** [comment]
Go to the private app settings page in the shopify admin and copy the full example URL.

**Comment by internalfx** [comment]
which will include the API keys

**Comment by emiremiroglu** [comment]
It is nice to have at least an example somewhere, I managed to make it work but still my auth string has orders.json at the end which feels weird.
Thank you!

**Comment by internalfx** [comment]
That should be fine....

Rather than ask you for multiple pieces of information, quickshot parses the URL for you to properly configure itself.
