### ISSUE TITLE
qs pages upload error @ version 3.3.1

### ISSUE THREAD

**Issue by royvn** [internalfx/quickshot#71]
## Expected
* Download pages from target A
* Upload the downloaded pages from target A to target B

## Steps to reproduce error
1. Download pages from target A. (works)
2. Upload the downloaded pages to target B with `quickshot pages upload` (fails)

It shows the error message: `404 Not Found - Are you sure "undefined" is a valid Shopify theme path?`

## Issue 

Got it temporarily working with manual changes.

Not existing pages (on the target B environment) need to be created with a POST to /admin/api/2020-01/pages.json. (See https://shopify.dev/docs/admin-api/rest/reference/online-store/page?api%5Bversion%5D=2020-01#create-2020-01)

Changed file src/commands/pages/upload.js
```
const res = await to(requestify(target, {
  method: 'post',
  url: `/pages.json`,
  body: {
    page: _.pick(page, 'id', 'body_html', 'author', 'title', 'handle')
  }
}))
```

BTW thanks for the tool!

**Comment by internalfx** [comment]
Thanks @royvn !

I hadn't tested copying from one shop to another using this.

**Comment by internalfx** [comment]
This should be fixed in latest version
