### ISSUE TITLE
Allow BrowserSync or reaload on watch

### ISSUE THREAD

**Issue by eddysims** [internalfx/quickshot#76]
Just started looking into Quickshot, and it seems like a great tool. Is there a way to reload the browser on watch? Similar to a browser sync type tool?

**Comment by joshuaiz** [comment]
@eddysims If you scroll to the bottom of this thread and follow the suggestion you can get browser reloading with BrowserSync:

https://github.com/Shopify/slate/issues/1055

**Comment by eddysims** [comment]
I have created a PR to handle this is a nicer way

https://github.com/internalfx/quickshot/pull/77

**Comment by internalfx** [comment]
fixed in qs 3.6.0
