### ISSUE TITLE
Slate - End of Support (January 2020)

### ISSUE THREAD

**Issue by stevenventimiglia** [internalfx/quickshot#79]
@internalfx - What is the current status of Quickshot since Slate has been deprecated due to Shopify's updated section theme architecture.

**Comment by internalfx** [comment]
Quickshot does not depend on slate. I'm not even sure how you could use the two together (I've never used slate).

**Comment by internalfx** [comment]
I realized I didn't fully answer your question...

Quickshot still works great. Try it! As far as I know it is the best "edit local files" and "see your shop update" solution there is out there.
