### ISSUE TITLE
Updates to Shopify theme editor causing additional downloads with --sync

### ISSUE THREAD

**Issue by joshuaiz** [internalfx/quickshot#80]
Hello,

It looks like Shopify updated the theme editor in the admin and the update seems to be causing issues with `theme watch --sync`. 

When `--sync` is active and I save a file locally, QS is downloading the theme editor file which is overwriting local changes. I have to save a few times to get it to "stick". These files shouldn't be downloaded...I'm updating them locally and then saving - there is no processing e.g. with an scss.liquid or js.liquid file.

![CleanShot 2020-10-08 at 16 37 02@2x](https://user-images.githubusercontent.com/1096738/95516208-83699580-0984-11eb-8302-65722fc0645e.jpg)

I just started noticing this today and then saw this message in the Shopify admin:

![CleanShot 2020-10-08 at 16 37 52@2x](https://user-images.githubusercontent.com/1096738/95516281-a1cf9100-0984-11eb-966e-10deca9e392a.jpg)

I'm going to contact Shopify Plus support but just wanted to see if anyone else is seeing this and if there's anything we can do to fix.

Thanks!

**Comment by joshuaiz** [comment]
Contacted Shopify Plus support and was able to opt out of the new Theme Editor. Quickshot is working as normal. 

This may not be a viable solution long term if the Shopify editor is updated.

**Comment by internalfx** [comment]
@joshuaiz is this still an issue?

**Comment by joshuaiz** [comment]
No this was resolved. You can close.
