### ISSUE TITLE
errors when using --sync flag

### ISSUE THREAD

**Issue by EcomGraduates** [internalfx/quickshot#81]
![image](https://user-images.githubusercontent.com/74157486/113043786-90f91e80-9162-11eb-810e-40abf10e685c.png)

I'm not very sure why this is happening or what's causing it

**Comment by joshuaiz** [comment]
^^ Getting this too.

**Comment by internalfx** [comment]
@EcomGraduates @joshuaiz Is this still an issue?

**Comment by joshuaiz** [comment]
Just did a quick test and it looks like this is no longer happening for me.

**Comment by internalfx** [comment]
@joshuaiz Good to hear, feel free to re-open if it comes back.
