### ISSUE TITLE
More helpful messages when Shopify throws a 422 Error

### ISSUE THREAD

**Issue by internalfx** [internalfx/quickshot#9]
A 422 usually means a syntax error in uploaded liquid code. Quickshot should display a more helpful error message.

**Comment by rickydazla** [comment]
@internalfx the API must send more info back as in the [textmate bundle](https://github.com/meeech/shopify.tmbundle) you can get something like this...

![screen shot 2015-04-06 at 19 54 29](https://cloud.githubusercontent.com/assets/486590/7016323/ec15ba9e-dc96-11e4-851a-7641b7b264f2.png)
