### ISSUE TITLE
Unable to run quickshot 3.6.0 or 4.0.0

### ISSUE THREAD

**Issue by trajce** [internalfx/quickshot#90]
I've updated from `3.5.0` to both `3.6.0` and `4.0.0` and when I try running `qs` or any qs related command in an existing project I'm getting `Error: Shop configuration is from an older version of quickshot. You need to run 'quickshot config' again.`
I tried deleting the qs files but still getting similar config messages. Rolling back to `3.5.0` works fine.

**Comment by internalfx** [comment]
@trajce you need to run `quickshot config` or `qs config` for short.

**Comment by internalfx** [comment]
Then select `save configuration and exit` to rewrite the new config file

**Comment by internalfx** [comment]
@trajce ok, I see what the problem is now, disregard above.

**Comment by trajce** [comment]
That still gives the same message. `Error: Shop configuration is from an older version of quickshot. You need to run 'quickshot config' again.` And if I delete the config / ignore files, then the message is `Error: Shop configuration is missing, have you run 'quickshot configure'?`

Here is the output
```
> quickshot config        
Error: Shop configuration is from an older version of quickshot. You need to run 'quickshot config' again.
=== START OF OUTPUT ===
Error: Shop configuration is from an older version of quickshot. You need to run 'quickshot config' again.
at loadConfig (file:///C:/Users/the-user/AppData/Roaming/nvm/v18.0.0/node_modules/quickshot/src/helpers.js:32:13)
at async default (file:///C:/Users/the-user/AppData/Roaming/nvm/v18.0.0/node_modules/quickshot/src/main.js:28:3)
at async file:///C:/Users/the-user/AppData/Roaming/nvm/v18.0.0/node_modules/quickshot/bin/quickshot.js:9:18
==== END OF OUTPUT ====
```

**Comment by internalfx** [comment]
v4.0.1 Published

**Comment by internalfx** [comment]
@trajce Please re-open if your issue persists.
